# conda env create -f environment.yml
name: diff_hysteresis
channels:
  - gpytorch
  - pytorch
  - conda-forge
dependencies:
  - botorch==0.4.0
  - gpytorch==1.5.0
  - ipykernel
  - ipywidgets
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - pytorch
  - scipy
  - pip:
    - pygmsh
